server: 
  address: ":9080"
  cidr_ip_whitelist: "*"
database:
  host: "localhost"
  port: 5432
  user: "mark"
  password: "123456"
  dbname: "wingo"
  ssl: "disable" # require, verify-full, verify-ca
log:
  level: debug
secrets:
  admin: './secrets/pub.admin.pem'
  user: './secrets/pub.user.pem'
redis:
  address: "localhost:6379"
  pool:  0 # zero = 10 * cpu cores
  timeout:
    dial: "5s"
    read: "3s"
    write: "3s"
    pool: "4s"
    idle: "5m"
app:
  answer_delay: 15
  answer_threshould: 5
  next_contest:
    default_hour: "9"
    default_min: "30"
    default_sec: "00"
  referral_tickets: 0
  referral_correctors: 0
  referer_tickets: 0
  referer_correctors: 0
  new_user_ticket: 0
  new_user_corrector: 0

emq:
  base: "http://localhost:8080"
  auth:
    username: "wingo"
    password: "Mjg1ODk1MDY4NDE5NDM0MTA4NTA0MDQ0MjI5NjQ0MTI0MTG"