server: 
  address: ":9080"
database:
  host: "localhost"
  port: 5432
  user: "mark"
  password: "123456"
  dbname: "wingo"
  ssl: "disable" # require, verify-full, verify-ca
log:
  level: debug
secrets:
  admin: './secrets/pub.admin.pem'
  user: './secrets/pub.user.pem'
redis:
  address: "localhost:6379"
  pool:  0 # zero = 10 * cpu cores
  timeout:
    dial: "5s"
    read: "3s"
    write: "3s"
    pool: "4s"
    idle: "5m"